apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: staging-release
  namespace: kosina
spec:
  chart:
    spec:
      chart: .
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: kosina-apps       
  interval: 1m0s
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kosina-apps
  namespace: kosina
spec:
  interval: 1m0s
  url: https://github.com/kevindarzini/kosina-apps
  ref:
    branch: master
