---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kosina-app
  namespace: flux-system
spec:
  interval: 30s
  path: ./apps/kosina-app/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kosina-gitops
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/kevindarzini/kosina-gitops
